CREATE TABLE "CAF_ADMIN"."FRC_REQUEST_DATA" 
   (	"ID" RAW(16) DEFAULT SYS_GUID(), 
	"VENDORID" VARCHAR2(50), 
	"VENDORMSISDN" VARCHAR2(10), 
	"REQID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GSMNO" VARCHAR2(10), 
	"REQDATE" DATE, 
	"MPIN" VARCHAR2(100), 
	"FRCAMT" NUMBER(6,0), 
	"CSCCODE" VARCHAR2(50), 
	"EDATE" DATE, 
	"IN_STATUS" VARCHAR2(3), 
	"IN_DATE" DATE, 
	"PYRO_STATUS" VARCHAR2(3), 
	"PYRO_DATE" DATE, 
	"SS_STATUS" VARCHAR2(3), 
	"SS_DATE" DATE, 
	"VAS_TRANS_ID" NUMBER(15,0), 
	"TRANSACTIONID" NUMBER(15,0), 
	"SOURCE_MSISDN" VARCHAR2(10), 
	"DEST_MSISDN" VARCHAR2(10), 
	"DENOMINATION" NUMBER(6,0), 
	"FINAL_STATUS" VARCHAR2(3), 
	"RECORDID" NUMBER(10,0), 
	"REMARKS" VARCHAR2(100), 
	"PYRO_TRANS_ID" NUMBER(15,0), 
	"MSG_AFTERREQ" VARCHAR2(500), 
	"MSG_AFTERTR" VARCHAR2(500), 
	"REFID" NUMBER(15,0), 
	"CIRCLE_CODE" NUMBER(2,0), 
	"MSG2PYRO" VARCHAR2(500), 
	"OTPMSG" VARCHAR2(100), 
	"REPLYMSG" VARCHAR2(100), 
	"REPLYRECVD_DATE" DATE, 
	"FRCSTATUS" VARCHAR2(1), 
	"FRCDATE" DATE, 
	"IPDETAIL" VARCHAR2(20), 
	"PYRO_FINAL_DATE" DATE, 
	"SELLER_COMM" NUMBER, 
	"FRA_COMM" NUMBER, 
	"MPIN_LENGTH" NUMBER, 
	"PUSH_FLAG" VARCHAR2(10) DEFAULT 'N', 
	"PUSH_REMARKS" VARCHAR2(200), 
	"PUSH_DATE" DATE, 
	"CAF_SERIAL_NO" VARCHAR2(30) NOT NULL ENABLE, 
	"UPDATED_TS" TIMESTAMP (6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAF_TS"  ENABLE, 
	 CONSTRAINT "FRC_REQUEST_DATA_REQDATE_CAF_SERIAL_NO" UNIQUE ("REQDATE", "CAF_SERIAL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAF_TS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CAF_TS" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "CAF_ADMIN"."TRG_FRC_REQUEST_DATA_UPDATED_TS" 
BEFORE UPDATE ON FRC_REQUEST_DATA
FOR EACH ROW
BEGIN
    :NEW.updated_ts := CURRENT_TIMESTAMP;
END;